doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: 'dbname_test'
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db